name: Generate and upload report to KTU Moodle

env:
  CONFIG_FILENAME: report.toml
  ASSIGNMENT_ID: 1499
  MOODLE_FILENAME: IF-1-1_Rokas_Puzonas.pdf
  DOTNET_VERSION: 3.0.103

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'report.toml'
  #     - 'Lab1/Lab1.TouristInformationCenter/**'
  #     - 'Lab2/Lab2.TouristInformationCenter/**'
  #     - 'Lab3/Lab3.TouristInformationCenter/**'
  #     - 'Lab4/Lab4.TouristInformationCenter/**'
  #     - 'Lab5/Lab5.TouristInformationCenter/**'

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate report
      uses: RokasPuzonas/ktu-oop-report-generator@v1.0.3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        config-filename: ${{ env.CONFIG_FILENAME }}
        output-filename: report.pdf

    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: report.pdf

    - name: Upload report to moodle
      uses: RokasPuzonas/ktu-moodle-assignment-upload@v1.0.3
      with:
        assignment-id: ${{ env.ASSIGNMENT_ID }}
        target-filename: report.pdf
        upload-filename: ${{ env.MOODLE_FILENAME }}
        ktu-username: ${{ secrets.KTU_USERNAME }}
        ktu-password: ${{ secrets.KTU_PASSWORD }}
