name: Generate and upload report to KTU Moodle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate report
      uses: RokasPuzonas/ktu-oop-report-generator@v1.0.1
      with:
        dotnet-version: 3.0.103
        config-filename: report.toml
        output-filename: report.pdf
    - name: Upload report
      uses: RokasPuzonas/ktu-moodle-assignment-upload@v1.0.0
      with:
        assignment-id: 1499
        target-filename: report.pdf
        upload-filename: IF-1-1_Rokas_Puzonas.pdf
        ktu-username: ${{ secrets.KTU_USERNAME }}
        ktu-password: ${{ secrets.KTU_PASSWORD }}

